### ISSUE TITLE
CURLE_RECV_ERROR when performing HTTPS POST with OpenSSL 1.1.1t and libcurl 8.1.0

### ISSUE THREAD

**Issue by injertao** [curl/curl#11181]
Hello,

I'm encountering an issue when using libcurl 8.1.0 with OpenSSL 1.1.1t. When I perform a POST operation over HTTPS, I receive a CURLE_RECV_ERROR. However, if I do not set any POST fields or if I remove the 'https', the error does not occur.

```
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);

        //SSL
        curl_easy_setopt(curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);//CURL_SSLVERSION_SSLv3


        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);

        struct curl_slist* headers = NULL;


        headers = curl_slist_append(headers, "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36");


        headers = curl_slist_append(headers, "Accept-Encoding: identity");

        headers = curl_slist_append(headers, "Content-Type: application/x-www-form-urlencoded");



        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
```

**Comment by injertao** [comment]
我使用了` curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2_0);，`但问题仍然存在。

**Comment by bagder** [comment]
Then please try 8.1.1 and see if that makes the behavior different!

**Comment by injertao** [comment]
> Then please try 8.1.1 and see if that makes the behavior different!

the problem still persists.

**Comment by injertao** [comment]
```
string tCurl::UploadString(const std::string& url, std::string payload, string* newUrl)
{
    string response;
    //CURL* curl = curl_easy_init();
    if (curl) {
        curl_easy_setopt(curl, CURLOPT_URL, url.c_str()); 

        curl_easy_setopt(curl, CURLOPT_TIMEOUT, 15L); 

        curl_easy_setopt(curl, CURLOPT_UPLOAD, 0L);
        /* now specify which file to upload */
        //curl_easy_setopt(curl, CURLOPT_READDATA, payload.c_str());

        /////* provide the size of the upload */
        //curl_easy_setopt(curl, CURLOPT_INFILESIZE_LARGE, payload.length());


        curl_easy_setopt(curl, CURLOPT_POST, 1L);
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, payload.c_str());//
        //if (cookies)
        //{

        //    curl_slist* nc = cookies;
        //    while (nc) {
        //        curl_easy_setopt(curl, CURLOPT_COOKIELIST, nc->data);
        //        nc = nc->next;
        //    }
        //}
        //else
        {

            
        }
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback); 
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);  // 

        //curl_easy_setopt(curl, CURLOPT_CAINFO, "C:\\Work\\Code\\cacert-2023-01-10.pem");
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

        //SSL
        curl_easy_setopt(curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_SSLv3);//CURL_SSLVERSION_SSLv3


        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);

        struct curl_slist* headers = NULL;
        headers = curl_slist_append(headers, "Content-Type: application/x-www-form-urlencoded");

        headers = curl_slist_append(headers, "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36");


        headers = curl_slist_append(headers, "Accept-Encoding: identity");

        



        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);

        //curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
        //curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_NONE);


        CURLcode res = curl_easy_perform(curl);
        if (res == CURLE_OK) {
            //std::string errorText = "curl_easy_perform() failed: " + std::string(curl_easy_strerror(res));
            //MessageBoxA(NULL, errorText.c_str(), "Error", MB_OK);

           // curl_easy_getinfo(curl, CURLINFO_COOKIELIST, &cookies);
        }
        if (newUrl)
        {
            char* urlTMP = NULL;
            curl_easy_getinfo(curl, CURLINFO_EFFECTIVE_URL, &urlTMP);
            if (urlTMP)
                *newUrl = urlTMP;
        }


        curl_slist_free_all(headers);
        
    }
    return response;
}
```
I have almost reviewed all the articles on Google, but I still haven't found a solution to my problem.

**Comment by bagder** [comment]
Please tell us how to reproduce this problem.

**Comment by bagder** [comment]
What does a verbose output show?

When I try to access this server I get:
~~~
curl: (35) OpenSSL/3.0.8: error:0A000152:SSL routines::unsafe legacy renegotiation disabled

**Comment by jay** [comment]
There was a POST issue that was fixed by #11200, it could be related. Please try curl from master branch.

**Comment by injertao** [comment]
> There was a POST issue that was fixed by #11200, it could be related. Please try curl from master branch.

It seems that it doesn't solve my problem because I've tried many previous versions,

**Comment by bagder** [comment]
> Yes, I am aware of this issue. I am using OpenSSL 1.1.1t

Yes. Which is why I asked: What does a verbose output show? `CURLOPT_VERBOSE` set to `1L`.

**Comment by injertao** [comment]
> > Yes, I am aware of this issue. I am using OpenSSL 1.1.1t
> 
> Yes. Which is why I asked: What does a verbose output show? `CURLOPT_VERBOSE` set to `1L`.

* !!! WARNING !!!
* This is a debug build of libcurl, do not use in production.
* STATE: INIT => CONNECT handle 0x2086e94e4b0; line 1951 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => RESOLVING handle 0x2086e94e4b0; line 1994 (connection #0)
* STATE: RESOLVING => CONNECTING handle 0x2086e94e4b0; line 2068 (connection #0)
*   Trying 202.80.107.13:443...
* Connected to tw.newlogin.beanfun.com (202.80.107.13) port 443 (#0)
* ALPN: offers http/1.1
* [CONN-0] Didn't find Session ID in cache for host HTTPS://tw.newlogin.beanfun.com:443
* [CONN-0] Didn't find Session ID in cache for host HTTPS://tw.newlogin.beanfun.com:443
* [CONN-0] Added Session ID to cache for HTTPS://tw.newlogin.beanfun.com:443 [server]
* SSL connection using TLSv1.2 / AES256-SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: C=TW; ST=Taipei; L=Taipei; O=Gamania Digital Entertainment Co., Ltd.; CN=tw.newlogin.beanfun.com
*  start date: Feb 13 09:11:06 2023 GMT
*  expire date: Mar 16 09:11:05 2024 GMT
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* using HTTP/1.x
* STATE: CONNECTING => PROTOCONNECT handle 0x2086e94e4b0; line 2112 (connection #0)
* STATE: PROTOCONNECT => DO handle 0x2086e94e4b0; line 2142 (connection #0)
> POST /login/id-pass_form.aspx?skey=2023052f6b52295d0a46 HTTP/1.1

Host: tw.newlogin.beanfun.com

Accept: */*

Cookie: ASP.NET_SessionId=4avkosjbqof0yl55hciafe45; dddstop=1

Content-Length: 1220

Content-Type: application/x-www-form-urlencoded



* STATE: DO => DID handle 0x2086e94e4b0; line 2236 (connection #0)
* STATE: DID => PERFORMING handle 0x2086e94e4b0; line 2354 (connection #0)
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Found

* Please rewind output before next send
< Location: https://tw.hicdn.beanfun.com/beanfun/beanfun/ErrorPage/500.html

< Connection: close

< 

* OpenSSL SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)
* [CONN-0] readwrite_data() -> 56
* [CONN-0] Curl_readwrite() -> 56
* multi_done: status: 56 prem: 1 done: 0
* multi_done, not re-using connection=0, forbid=0, close=1, premature=1, conn_multiplex=0
* The cache now contains 0 members
* Curl_disconnect(conn #0, dead=1)
* Closing connection 0
* Expire cleared (transfer 0x2086e94e4b0)

**Comment by injertao** [comment]
@bagder 
I am currently working on replicating the functionality of a C# WebClient code in C++ using libcurl. 
I am confident that the content of my POST request is correct, but I am unsure where the problem lies. Interestingly, even when I change the content of the POST request to an obviously invalid value, curl_easy_perform still returns normally. 
I am beginning to suspect that the issue might be related to the length of the POST request.

**Comment by bagder** [comment]
> OpenSSL SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)

This is a missing `close_notify` from TLS when the connection is closed. Obviously, this error does not happen on non-debug builds as the text explains. Still, this is a misbehaving server.

You could try with a non-debug build or by commenting out that check and see if it works better for you.

>  I am beginning to suspect that the issue might be related to the length of the POST request.

I think that is unrelated for curl but may of course make the server act differently so maybe it changes behavior based on that.

**Comment by injertao** [comment]
> > OpenSSL SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)
> 
> This is a missing `close_notify` from TLS when the connection is closed. Obviously, this error does not happen on non-debug builds as the text explains. Still, this is a misbehaving server.
> 
> You could try with a non-debug build or by commenting out that check and see if it works better for you.
> 
> > I am beginning to suspect that the issue might be related to the length of the POST request.
> 
> I think that is unrelated for curl but may of course make the server act differently so maybe it changes behavior based on that.

Thank you for your response. However, I have tried the non-debugging version and I am still unable to properly retrieve the web page content. Logically, whether it's the POST parameters or other previous issues, they should not be the reason for not being able to retrieve the content. Could you possibly spare some time to conduct a simple test? I have provided the POST content and address above.

**Comment by injertao** [comment]
If I sponsor this project, can my problem be resolved as soon as possible?
@bagder

**Comment by dfandrich** [comment]
If you need time-bounded assistance on a specific problem with a guarantee, you're probably looking for [commercial support](https://curl.se/support.html).

**Comment by bagder** [comment]
> Could you possibly spare some time to conduct a simple test?

The site requires use of legacy renegotiation which my curl + OpenSSL combo does not do. Is your 1.1.1 version doing them and if so, what does it say the problem is? You did not show us the verbose output from such an attempt.

If you buy my support I could accept working on this issue with a legacy OpenSSL version.

**Comment by injertao** [comment]
Yes, I need to purchase your support. How should I proceed, and what is the price for it? @bagder

**Comment by bagder** [comment]
I sell commercial curl support via WolfSSL. See [details](https://curl.se/support.html) on the website.

**Comment by injertao** [comment]
I have previously sent you an email expressing my interest in purchasing support, but I have not received a response. @bagder

**Comment by bagder** [comment]
Then please send a new email. I have not seen any.
