### ISSUE TITLE
Socket gets closed twice when connection is dead

### ISSUE THREAD

**Issue by JayDommaschk** [curl/curl#13086]
### I did this

Hello,
while testing some application of mine, I was using some laptop in my network as an sftp server. At some point I shut down this laptop and later initiated another sftp upload. This caused some issues in my application because it seems a socket gets closed twice. I wrote a minimal test program for this:

```c
#include <curl/curl.h>
#include <stdio.h>
#include <sys/stat.h>
#include <unistd.h>

int main()
{
    const char *path = "/tmp/test.txt";
    const char *serverIp = "192.168.0.104";
    const char *targetPath = "test";
    const char *userName = "testUser";
    const char *pass = "pass";
    const char *knownHosts = "/home/jay/.ssh/known_hosts";

    FILE *file = fopen(path, "rb");
    struct stat file_info;
    stat(path, &file_info);

    char SERVER_URL[512];
    CURLcode res = CURLE_OK;
    CURL *curl = curl_easy_init();

    curl_version_info_data *ver = curl_version_info(CURLVERSION_NOW);
    printf("curl version: %u.%u.%u\n", (ver->version_num >> 16) & 0xff,
                                       (ver->version_num >> 8) & 0xff,
                                       ver->version_num & 0xff);

    curl_easy_setopt(curl, CURLOPT_USERNAME, userName);
    curl_easy_setopt(curl, CURLOPT_PASSWORD, pass);

    snprintf(SERVER_URL, sizeof(SERVER_URL), "sftp://%s:%s/~/%s", serverIp, "22", targetPath);
    curl_easy_setopt(curl, CURLOPT_URL, SERVER_URL);

    curl_easy_setopt(curl, CURLOPT_INFILESIZE_LARGE, (curl_off_t)(file_info.st_size));
    curl_easy_setopt(curl, CURLOPT_FTP_CREATE_MISSING_DIRS, CURLFTP_CREATE_DIR_RETRY);
    curl_easy_setopt(curl, CURLOPT_SSH_KNOWNHOSTS, knownHosts);

    curl_easy_setopt(curl, CURLOPT_READDATA, file);
    curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);

    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

    res = curl_easy_perform(curl);
    printf("curl result: %s (%d)\n", curl_easy_strerror(res), res);

    //wait 1 minute to shut down server
    printf("begin wating\n");
    sleep(60);
    printf("finished waiting\n");

    res = curl_easy_perform(curl);
    printf("curl result: %s (%d)\n", curl_easy_strerror(res), res);
    curl_easy_cleanup(curl);
}
```

If I compile this as curlTest and run with `strace -e trace=listen,accept,bind,socket,open,close ./curlTest` and go and turn off the server while the program waits, I see

```
curl version: 8.7.0
socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 6
*   Trying 192.168.0.104:22...
* Connected to 192.168.0.104 (192.168.0.104) port 22
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 7
close(7)                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 7
close(7)                                = 0
close(7)                                = 0
close(7)                                = 0
close(7)                                = 0
close(8)                                = 0
close(7)                                = 0
* User: testUser
* Known hosts: /home/jay/.ssh/known_hosts
close(7)                                = 0
close(7)                                = 0
* SSH authentication methods available: public key, keyboard-interactive, password
* Authentication using SSH public key file
socket(AF_UNIX, SOCK_STREAM, 0)         = 7
close(8)                                = 0
* completed keyboard interactive authentication
* Authentication complete
* upload completely sent off: 1606 bytes
* Connection #0 to host 192.168.0.104 left intact
curl result: No error (0)
begin wating
finished waiting
* Connection 0 seems to be dead
close(6)                                = 0
close(7)                                = 0
* Closing connection
close(6)                                = -1 EBADF (Bad file descriptor)
* Hostname in DNS cache was stale, zapped
socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 6
*   Trying 192.168.0.104:22...
* connect to 192.168.0.104 port 22 from 192.168.0.105 port 55772 failed: No route to host
close(6)                                = 0
* Failed to connect to 192.168.0.104 port 22 after 14264 ms: Couldn't connect to server
* Closing connection
curl result: Couldn't connect to server (7)
close(4)                                = 0
close(5)                                = 0
+++ exited with 0 +++
```
(where I have omitted some close commands at the beginning that were related to loading shared libraries)
At the end, fd nr. 6 gets closed after connection 0 is deemed dead and again after the connection is closed.

By the way, I actually had to shut down the laptop. Merely turning off its wifi did not result in a dead connection. I am not sure what difference this makes on a low level, I am just mentioning it because it might be relevant for reproducing this issue.

### I expected the following

I expected that the socket would be closed just once.

### curl/libcurl version

Tested it with the current master (version 8.7.0) but also with the latest release (8.6.0) as well as the libcurl version that gets shipped on my OS (8.2.1).

### operating system

Ubuntu 23.10

**Comment by JayDommaschk** [comment]
> You start the first transfer to your laptop, then wait and close the server, then do the transfer again and it fails with "no route to host"? If I got this right, it looks correct to me.

all correct and I agree that the "no route to host" part is just what one would expect. I don't have an issue with that

> Note that the "EBADF (Bad file descriptor)" on double close is not nice, but it will not really affect anything else

in can affect other things. Not in my simple example above, sure. But for example if you have multiple threads running, then after the socket gets closed the first time, another thread might open a new fd (this might not even have to do with curl, depending on what your program is doing) which gets assigned that number (6 in my above example) which then gets closed by curl.
Another potential problem and actually what happened to me: My application actually uses the multi interface and the sockets are being handled by asio. If asio gets an error while trying to close a socket, it throws. Sure, this can be catched, but the fact that you would get this error that you have to handle specifically is...not nice indeed.

**Comment by icing** [comment]
@JayDommaschk agreed. I will look into what causes the second close.

**Comment by icing** [comment]
Which `libssh` variant and version are you using? There was a bug in earlier versions of libssh that closed the socket on a disconnect where it should not.

**Comment by bagder** [comment]
> here was a bug in earlier versions of libssh that closed the socket on a disconnect where it should not.

There was, but since ef22d5c42a25e, this should be fixed... and @JayDommaschk says he sees this problem in current git as well.

**Comment by bagder** [comment]
@JayDommaschk seeing your full `curl -V` output would be helpful!

**Comment by JayDommaschk** [comment]
```
curl 8.7.0-DEV (Linux) libcurl/8.7.0-DEV OpenSSL/3.0.10 zlib/1.2.13 libidn2/2.3.4 libssh/0.10.5/openssl/zlib
Release-Date: [unreleased]
Protocols: dict ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s scp sftp smtp smtps tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets
```

would be the 'curl -V' output for the last version I tested, that is, the current master.

After looking through the code a bit myself, I wonder if the problem could be that in 'prune_dead_connections' in 'lib/url.c' the call the 'Curl_disconnect' might close the socket since the comment above that function says that dead connections are being closed, but then in 'conn_shutdown' the sockets get (also?) closed. But be aware this is just the result of a rather superficial skimming of the code, so I might have just written complete nonsense.

**Comment by icing** [comment]
Opened an issue a libssh: https://github.com/canonical/libssh/issues/8

**Comment by bagder** [comment]
the libssh issue has been fixed and is supposed to be included in the next libssh release. Would be cool to test against their git version to verify...

**Comment by JayDommaschk** [comment]
I just tested with the most recent libssh master. Interestingly the original issue in my application seems gone, but if I run the simplified test program that I provided here, I still see that `close(6)                                = -1 EBADF (Bad file descriptor)` which is weird enough for me to wonder whether I did something wrong. To be super sure I installed a fresh virtual Ubuntu, but the failed close persisted. 

So I wonder whether anyone else can still reproduce this? Or anyone can even reproduce this at all?

At this point, I would be willing to dig into this myself if you guys have better/more important things to do, but for private reasons I will likely not have time for this until end of April.

**Comment by icing** [comment]
@JayDommaschk would appreciate you following up on this when you find the time.

**Comment by JayDommaschk** [comment]
I found a few minutes today, so I tested again and suddenly it worked. Turned out I messed up my test environment last time. Sorry about that!

So I can confirm that the double close is gone with the latest libssh version and everything works beautifully now. Thanks to everyone involved and sorry again for the false alarm yesterday
