### ISSUE TITLE
Adopt `SI` and `IEC` standards for size display

### ISSUE THREAD

**Issue by Fd929c2CE5fA** [curl/curl#19448]
### I did this

The topic was originally brought up here: 
- https://github.com/curl/curl/issues/19431#issuecomment-3508965571
- https://github.com/curl/curl/pull/19433#issuecomment-3509040311

But it is more suitable to be raised as an independent issue.

https://en.wikipedia.org/wiki/Binary_prefix
https://en.wikipedia.org/wiki/SI_prefix
https://en.wikipedia.org/wiki/IEC_80000-13

> Prior to the 1999 IEC standard, some industry organizations, such as the [Joint Electron Device Engineering Council](https://en.wikipedia.org/wiki/JEDEC_memory_standards#Unit_prefixes_for_semiconductor_storage_capacity) (JEDEC), noted the common use of the terms kilobyte, megabyte, and gigabyte, and the corresponding symbols KB, MB, and GB in the binary sense, for use in storage capacity measurements. However, other computer industry sectors (such as [magnetic storage](https://en.wikipedia.org/wiki/Magnetic_storage)) continued using those same terms and symbols with the decimal meaning. Since then, the major standards organizations have expressly disapproved the use of SI prefixes to denote binary multiples, and recommended or mandated the use of the IEC prefixes for that purpose, but the use of SI prefixes in this sense has persisted in some fields.

As mentioned in the wiki, we are using the `SI` prefixes to describe binary multiples (1024), which is against the standards and continues to confuse people.

Note here that `JEDEC` uses `KB` instead of `kB`, and this standard is no longer recommended and it has caused a lot of confusion.

Of course we can question why we want to change the usage of a software that has been used for decades or even predates the birth of these standards, just like Windows and hard disk manufacturers, which have never used the unit prefixes recommended by the standards.

I don’t want to defend or justify this, but following standards is always a small step toward reducing confusion.

Change is never easy, but it is possible to adopt standards without breaking anything. Even if we worry about wreaking new havoc by changing defaults, we can put standards behind options and give people choices.

So, please at least consider implementing an option/environment variable that allows one to explicitly specify the `SI` or `IEC` standard.

For example:
```sh
CURL_UNIT_PREFIX=SI
CURL_UNIT_PREFIX=IEC
--unit-prefix "SI" or "IEC" (Use internal non-standard unit prefixes by default)
```

As adoption rates change, perhaps one day in the future people decide it's time to change the default.

**Finally, I would like to express my highest respect to all project contributors and founders. Thank you for creating and continuing to maintain this project! ❤️🙏🙇**

### curl/libcurl version

~curl 8.17.0

### operating system

N/A

**Comment by jay** [comment]
The short form k,M,G has always been ambiguous, I don't see it as "wrong" though

**Comment by Fd929c2CE5fA** [comment]
> The short form k,M,G has always been ambiguous

This is why we need standards, and why we should try to adopt and adhere to them.

`SI` prefixes are explicitly used to represent decimal numbers, which are widely used and well known around the world.

> Since then, the major standards organizations have expressly disapproved the use of SI prefixes to denote binary multiples, and recommended or mandated the use of the IEC prefixes for that purpose, but the use of SI prefixes in this sense has persisted in some fields.

As the wiki says, it is still used in some fields and conflicts with the standards, `curl` being one of them.

Like I wrote in the OP, I don't want to argue whether it's right or wrong, but we now have better standards that could eliminating ambiguous usage and all kind of confusion, so why don't we try to adopt them?

I don't see any chance of breaking or having side effects when allowing users to explicitly specify unit-prefix standard via environment variables or option.

This is the main intention of this issue. It is not to argue about right or wrong or destructive changes, but to constructively adopt standards while keep compatibility and allow users to actively opt-in.

Thanks for reviewing, I hope this provides some more clarity to this issue.

**Comment by bagder** [comment]
I put up a casual poll on Mastodon to get a feel for how people feel about this subject:

https://mastodon.social/@bagder/115535765105053532

(it does not mean much and it is not serious)

**Comment by Fd929c2CE5fA** [comment]
> I put up a casual poll on Mastodon to get a feel for how people feel about this subject

Thanks, I had the same thought another day and that's a good one.

**Comment by Fd929c2CE5fA** [comment]
I also did something else the another day: I searched if there a widely used environment variable, such as a system-level one, that would allow all software to reference this preference.

But I didn't find one, and I actually think that would be better than simply setting a CURL environment variable.

Perhaps we should use a more widely applicable environment variable and push for it to become a new standard to end the chaos in user systems. What I mean is to encourage others to refer the same environment variables.

For example:
```
UNIT_PREFIX_STANDARD=SI
UNIT_PREFIX_STANDARD=IEC
```

This is, in some ways, much better than encouraging people to patch or providing a build/compilation parameter.

The user should be the one choosing their preferences, not the developer or the operating system. Both `SI` and `IEC` are standards, and they are convertible and unambiguous.

---

_As an additional read, these pages provide a good record of the current situation, as well as people's past efforts and research:_
- https://wiki.ubuntu.com/UnitsPolicy  (Thanks to @julian-klode for [linking](https://mastodon.social/@juliank/115536595317626979) it)

**Comment by bagder** [comment]
We use *single letters* for units because I've tried to cram in a lot of information on the line and I want the line to fit within 80 columns. Single letter units for bytes is not correct for either base, 1000 or 1024. It should be `kB` or `KiB` but we use `k` etc. 

Switching to three-letter units for the six numbers would add twelve more letters. I think that would be a loss.

**Comment by Fd929c2CE5fA** [comment]
> We use single letters for units because I've tried to cram in a lot of information on the line and I want the line to fit within 80 columns.
> Switching to three-letter units for the six numbers would add twelve more letters. I think that would be a loss.

Deeply understand and appreciate your efforts, it's really pretty neat. 👍

Just two quick thoughts that came to mind:

- In a terminal wider than 80 columns, might using only 80 columns be an underutilization of space?
  - Maybe a new option is needed to control this

- For the case of retaining 80 columns, maybe splitting into two rows is the way to go? Like:

`Default`:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12345M 100 12345M   0     0  12345k    0   1:07:43  0:00:19  1:07:24 12345k
```
`IEC`:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12345  100 12345    0     0  12345     0   1:07:43  0:00:19  1:07:24  12345
      MiB        MiB          B  KiB/s     B/s                            KiB/s
```

**Comment by Fd929c2CE5fA** [comment]
Also, and this is an off-topic discovery, during startup it may actually take at least 3 sideways jumps before finally aligning, it's very noticeable on slow networks:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0   0     0   0     0     0     0  --:--:-- --:--:-- --:--:--     0

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 16097M   0 61368   0     0 26922     0    7d 06h  0:00:02   7d 06h 26915

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 16097M   0 196855   0     0 48398     0  96:52:48  0:00:04 96:52:44 48391

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 16097M   0  1134k   0     0 191036     0  24:32:38  0:00:06 24:32:32 242203
```

**Comment by bagder** [comment]
> an off-topic discovery

That bug is already fixed I believe.

**Comment by bagder** [comment]
We can only update the last line without using trickery we don't want to do. So the units would in that case have to be above the numbers.

**Comment by Fd929c2CE5fA** [comment]
> That bug is already fixed I believe.

I don't know, it still exists in the current latest curl 8.17.0.

> We can only update the last line without using trickery we don't want to do. So the units would in that case have to be above the numbers.

Units are dynamic with speed, so they need to be updated no matter where they are placed. 
As for updating one row or multiple rows, I don't see why a trickery is needed? It's both just cursor control sequences and overlay printing.

**Comment by bagder** [comment]
> they need to be updated no matter where they are placed

The point is that we can only update the single last line.

> As for updating one row or multiple rows, I don't see why a trickery is needed?

cursor control is exactly the kind of *trickery* I referred to. curl only does carriage returns, no "cursor control" at all.

**Comment by Fd929c2CE5fA** [comment]
> cursor control is exactly the kind of _trickery_ I referred to. curl only does carriage returns, no "cursor control" at all.

"carriage returns" itself is cursor control, I don't understand why it is treated differently? Just because it's some kind of "syntactic sugar"?

Or are you essentially worried about their compatibility on different terminals? They are widely used in modern CLI tools.

If the experience of the modern users is sacrificed for a few edge cases, and prevent the adoption of standards to deliver information more accurately, I'm not sure if this is another loss?

I still want to emphasize that this proposal does not break any edge cases and compatibility, since it is hidden behind environment variables or options explicitly set by the user, and you could still keep the current used output format by default.

I think adopting standards will ultimately provide benefits to everyone, rather than replace people's choices. I raise this issue in hopes that there is a way to reduce confusion and not undermine other people's preferences and use cases.

I think the only burden here is that you don't want to maintain code and formatting that you don't like, so I'm okay with that. I understand that and maybe one day you will change your mind, but I won't force you to accept it now.

I still appreciate everything you put in. Let me close this annoying issue. Please feel free to reopen it if one day you want to reconsider the issue.
