### ISSUE TITLE
curl could not upload file to sftp server

### ISSUE THREAD

**Issue by GitYuanQu** [curl/curl#3408]
### I did this
[root@localhost src]# ls ../configure
../configure
[root@localhost src]# ./curl -V
curl 7.64.0-20181225 (x86_64-pc-linux-gnu) libcurl/7.64.0-20181225 OpenSSL/1.0.2p zlib/1.2.11 libssh2/1.7.0
Release-Date: 2018-12-25
Protocols: dict file ftp ftps gopher http https rtsp scp sftp smb smbs telnet tftp
Features: AsynchDNS Debug TrackMemory IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
[root@localhost src]# ./curl --url sftp://root:sys2009health@[fe80::42f2:e9ff:fe30:c17%eth0]/home ../configure
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: ..
[root@localhost src]# ./curl --url sftp://root:SYS2009health@[2002:97b:c2bb:830:10:240:196:14]/home ../configure
curl: (60) SSL peer certificate or SSH remote key was not OK
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
curl: (6) Could not resolve host: ..
[root@localhost src]# ping6 2002:97b:c2bb:830:10:240:196:14
PING 2002:97b:c2bb:830:10:240:196:14(2002:97b:c2bb:830:10:240:196:14) 56 data bytes
64 bytes from 2002:97b:c2bb:830:10:240:196:14: icmp_seq=1 ttl=64 time=0.341 ms
64 bytes from 2002:97b:c2bb:830:10:240:196:14: icmp_seq=2 ttl=64 time=1.71 ms
^C
--- 2002:97b:c2bb:830:10:240:196:14 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1365ms
rtt min/avg/max/mdev = 0.341/1.027/1.714/0.687 ms
[root@localhost src]# ping6 fe80::42f2:e9ff:fe30:c17%eth0
PING fe80::42f2:e9ff:fe30:c17%eth0(fe80::42f2:e9ff:fe30:c17) 56 data bytes
64 bytes from fe80::42f2:e9ff:fe30:c17: icmp_seq=1 ttl=64 time=2.48 ms
64 bytes from fe80::42f2:e9ff:fe30:c17: icmp_seq=2 ttl=64 time=0.353 ms
^C
--- fe80::42f2:e9ff:fe30:c17%eth0 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1466ms
rtt min/avg/max/mdev = 0.353/1.417/2.482/1.065 ms

### I expected the following
expect file could uploaded success

### curl/libcurl version

curl 7.64.0-20181225 (x86_64-pc-linux-gnu) libcurl/7.64.0-20181225 OpenSSL/1.0.2p zlib/1.2.11 libssh2/1.7.0
Release-Date: 2018-12-25
Protocols: dict file ftp ftps gopher http https rtsp scp sftp smb smbs telnet tftp
Features: AsynchDNS Debug TrackMemory IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

### operating system
ALL

**Comment by danielgustafsson** [comment]
> --url sftp://root:sys2009health@[fe80::42f2:e9ff:fe30:c17%eth0]/home

When using an IPv6 zone index in a URL it needs to be percent-encoded. If you instead use `[fe80::42f2:e9ff:fe30:c17%25eth0]`, does that work?

**Comment by GitYuanQu** [comment]
But I am so confused that when I return to use the former release 7.60.0 of curl, it could success:
====================================
[quyuan@localhost src]$ ./curl --url sftp://root:sys2009health@[fe80::42f2:e9ff:fe30:c17%eth0]/home/upload/configure  -T ../configure -k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1162k    0     0  100 1162k      0  3510k --:--:-- --:--:-- --:--:-- 3597k
100 1162k    0     0  100 1162k      0  3510k --:--:-- --:--:-- --:--:-- 3510k
[quyuan@localhost src]$ ./curl -V
curl 7.60.0 (x86_64-pc-linux-gnu) libcurl/7.60.0 OpenSSL/1.0.2p zlib/1.2.11 libssh2/1.7.0
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https rtsp scp sftp smb smbs telnet tftp
Features: AsynchDNS Debug TrackMemory IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
=================================================
but with newest snapshot, it will failed and show message "bad/illegal format of url":
=================================================
[quyuan@localhost src]$ ./curl --url sftp://root:sys2009health@[fe80::42f2:e9ff:fe30:c17%eth0]/home/upload/configure  -T ../configure -k
curl: (3) URL using bad/illegal format or missing URL
[quyuan@localhost src]$ ./curl -V
curl 7.64.0-20181225 (x86_64-pc-linux-gnu) libcurl/7.64.0-20181225 OpenSSL/1.0.2p zlib/1.2.11 libssh2/1.7.0
Release-Date: 2018-12-25
Protocols: dict file ftp ftps gopher http https rtsp scp sftp smb smbs telnet tftp
Features: AsynchDNS Debug TrackMemory IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
==============================================

this may caused by invalid parsing url which format is link local address.

**Comment by GitYuanQu** [comment]
> > --url sftp://root:sys2009health@[fe80::42f2:e9ff:fe30:c17%eth0]/home
> 
> When using an IPv6 zone index in a URL it needs to be percent-encoded. If you instead use `[fe80::42f2:e9ff:fe30:c17%25eth0]`, does that work?

it still failed:
======================
[quyuan@localhost src]$ ./curl --url sftp://root:sys2009health@[fe80::42f2:e9ff:fe30:c17%25eth0]/home/upload/configure  -T ../configure -k
curl: (3) URL using bad/illegal format or missing URL
========================

**Comment by GitYuanQu** [comment]
Hi， is there any progress？I saw your ticket 3411 build fail for a few days.

**Comment by bagder** [comment]
The URL parsing problem should be fixed in master now.

**Comment by bagder** [comment]
No further comments and I don't think there's any bug left here to fix. Closing.

**Comment by GitYuanQu** [comment]
Hi Bagder， sorry reply this so late, unfortunately this issue has not be fixed, we try this with newest build 7.64.1, it still failed, so please reopen this that we could track this again, thanks.

===========================
[xiaomen@localhost bin]$ ./curl -V
curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.0.2r zlib/1.2.11 libssh2/1.8.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https rtsp scp sftp smb smbs telnet tftp
Features: AsynchDNS Debug HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP TrackMemory UnixSockets
[xiaomen@localhost bin]$ ./curl --url sftp://root:SYS2009health@[fe80::20c:29ff:fe9c:409b%eth0] -T ../file_dx -k
curl: (3) URL using bad/illegal format or missing URL
=============================

**Comment by bagder** [comment]
Can you try again from current master? We've landed more fixes for zone id etc since the 7.64.1 release.

**Comment by GitYuanQu** [comment]
ok, I will update this if current master still could not solve it, thanks for your reply.

**Comment by GitYuanQu** [comment]
sorry Bagder, as our security team request, I need open a new ticket to track this issue, I will replicate with this and will close the new ticket if it could solved with new release, thanks.
