### ISSUE TITLE
Libcurl causes a segfault in MPD.

### ISSUE THREAD

**Issue by r3valkyrie** [curl/curl#4063]
### I did this
I attempted to troubleshoot this issue thinking it was a bug with MPD [here](https://github.com/MusicPlayerDaemon/MPD/issues/584). Apparently this is a bug in curl, and can't be fixed in MPD's end.

### I expected the following
When changing to a new stream, the program should switch to the next stream in the playlist without segfaulting.

### curl/libcurl version
curl 7.65.1 (x86_64-pc-linux-gnu) libcurl/7.65.1 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.36.0
Release-Date: 2019-06-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system
Archlabs kernel 5.1.12-arch1-1-ARCH

**Comment by falconindy** [comment]
Looks like https://bugs.archlinux.org/task/62892. It's already fixed in upstream curl, and in arch.

**Comment by bagder** [comment]
Presumed to be fixed in master already.

**Comment by r3valkyrie** [comment]
I'm going to try the latest git version, I'm still crashing on upstream curl.
