### ISSUE TITLE
incoming email metadata is garbled when IMAP envelope spread over two lines

### ISSUE THREAD

**Issue by KevinCarhart** [curl/curl#5965]
Hello, we have incorporated libcurl into the edbrowse project and we're an IMAP email client as well as other things.  When using IMAP for email and an envelope is spread across two lines, "curl only calls our callback function on the first line of the envelope and not the second ... Without the second half of the envelope there is no subject, no from, basically pretty useless ... I literally have to read the email to know what it is."

I am adapting this issue from a message from my colleague Karl.  Here are the version details for the environment where the problem is happening, and Karl's entire message follows.  Thank you, we appreciate the help.

___
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11
libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp
sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
HTTP2 UnixSockets HTTPS-proxy PSL

Linux EricCarmen 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux

I've only seen this on imap, and only comcast imap,
wherein the envelope is sometimes spread across two lines.
This doesn't happen in gmail imap.
curl is suppose to call our callback function with each chunk of data, and we put those chunks together,
and there is your web page or mail message or envelope or whatever it is.
All good, but curl only calls our callback function on the first line of the envelope and not the second.
Here is part of a run with db4. _[that's edbrowse notation]_
The verbose gives us all the curl traffic in and out.
You'll see both lines there, but, I have a debug print on the length of data in the callback function,
and you'll see the length of the first line and not the second.

Here's an envelope on one line, as most of them are.

curl>
A015 FETCH 4 ALL
curl<
* 4 FETCH (FLAGS ($HasNoAttachment) INTERNALDATE "01-Sep-2020 22:08:38 +0000" RFC822.SIZE 23730 ENVELOPE ("1 Sep 2020 22:00:31 +0000" "Wendy, I hope you're ready..." (("Publishers Clearing House" NIL "PublishersClearingHouse" "e.superprize.pch.com")) (("Publishers Clearing House" NIL "PublishersClearingHouse" "e.superprize.pch.com")) (("Publishers Clearing House" NIL "PublishersClearingHouse" "e.superprize.pch.com")) (("Wendy Dahlke" NIL "kwnre" "comcast.net")) NIL NIL NIL "<543.22827028370.202009012200313999957.0062470136@e.superprize.pch.com>"))
callback 555
A015 OK Fetch completed (0.001 + 0.000 secs).

Here's an envelope across two lines, with just one callback.

curl>
A016 FETCH 5 ALL
curl<
* 5 FETCH (FLAGS (\Seen $HasNoAttachment) INTERNALDATE "26-Aug-2020 21:14:43 +0000" RFC822.SIZE 41510 ENVELOPE ("26 Aug 2020 21:03:04 +0000" {77}
callback 147
=?utf-8?B?4p2XIE5vIGZ1cnRoZXIgYXR0ZW1wdHMgd2lsbCBiZSBtYWRl?= =?utf-8?B?Li4u?= (("Publishers Clearing House" NIL "PublishersClearingHouse" "e.superprize.pch.com")) (("Publishers Clearing House" NIL "PublishersClearingHouse" "e.superprize.pch.com")) (("Publishers Clearing House" NIL "PublishersClearingHouse" "e.superprize.pch.com")) (("Wendy Dahlke" NIL "kwnre" "comcast.net")) NIL NIL NIL "<543.22761811853.202008262102597548748.0037250599@e.superprize.pch.com>"))
A016 OK Fetch completed (0.001 + 0.000 secs).

Without the second half of the envelope there is no subject, no from, basically pretty useless.
I literally have to read the email to know what it is.

Any help appreciated.

Karl Dahlke

**Comment by bagder** [comment]
Hm, can perhaps da5ae38db0 from #5961 fix this case as well?

**Comment by bagder** [comment]
I believe this issue is already fixed. If we get no further feedback, I will close it soon.

**Comment by KevinCarhart** [comment]
Hi Daniel
I think we now have evidence that this is a separate imap issue from the issue fixed by #5961, "imap: set cselect_bits to CURL_CSELECT_IN initially" and still existing post 7.73.0.

Karl describes it like this:
Sometimes an email has an imap envelope across two lines, rather than one.
First line ends in {nnn}, and the first nnn bytes of the second line is the subject.
curl imap only presents the first line through its CURLOPT_HEADERFUNCTION.
(Fortunately, both lines, and the surrounding protocol, can be seen through CURLOPT_DEBUGFUNCTION.)
Our application can't present a proper envelope with just the first line. Subject and other information are not seen.
We need both lines reported through CURLOPT_HEADERFUNCTION.

I haven't found a way to reliably produce a 2 line envelope at the server, but they happen from time to time.

This was originally #5965, suggested that #5961 might fix it, but it does not.

Karl Dahlke

-------------------------------------------------------
I'll add that I can make the issue happen with libcurl4 7.74.0.  From your changelog, I saw that #5961 was fixed in 7.73.0, right?

So I wanted to see if it still happened on a curl from more recent than October.  I spun up a pristine ubuntu 21.04 from linode.  Then I issued:

`apt-get install edbrowse`

Verified the libcurl:

`apt-cache policy libcurl4`

`Installed: 7.74.0-1ubuntu2`

Then I configured edbrowse with the server strings and other strings for imap, and confirmed this to be working fine.

When I log in, go to my inbox, and read the froms/subjects I sporadically see messages with _0_ instead of a subject.

Thanks
Kevin
