### ISSUE TITLE
Unsupported response code in HTTP response since 7.79.0

### ISSUE THREAD

**Issue by glenndeb** [curl/curl#7738]
### I did this

I noticed a curl exception on the server due to an `cURL error 1: Unsupported response code in HTTP response`. When digging deeper, I found curl was updated on the 15th of september. Following up, I executed the exact CURL command in 7.78.0 and this worked.

`curl --location --request POST 'https://id.b2b.verizonmedia.com/identity/oauth2/access_token' -v`

### curl/libcurl version

7.79.0

[curl -V output]

curl 7.79.0 (x86_64-alpine-linux-musl) libcurl/7.79.0 OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 nghttp2/1.42.0
Release-Date: 2021-09-15
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

**Comment by bagder** [comment]
The "reason phrase" after the response code starts with a digit with is wrongly treated as the forth response code digit. Fix coming up!

**Comment by bagder** [comment]
I could perhaps also add that this happened because sscanf's `%d` skips leading whitespace which I had forgot when I did 5dc594e44f73b17

**Comment by ingwinlu** [comment]
Alpine already rolled out 7.79.0 which includes this defect. A fast release after the fix would be appreciated.

**Comment by jay** [comment]
> Alpine already rolled out 7.79.0 which includes this defect. A fast release after the fix would be appreciated.

7.79.1 patch release is next Wednesday

**Comment by bagder** [comment]
ah yes, good idea to pin! :+1:

**Comment by glenndeb** [comment]
Will this version be automatically available in the Alpine repository on Wednesday?

**Comment by bagder** [comment]
@glenndeb I think you need to ask the Alpine team about Alpine details. We as in the curl project will ship curl 7.79.1 on Wednesday Sep 22, 2021 (around 06:00 UTC). Then it is typically the job of distributions to build and package that release and put that update into their respective software reposutories. That procedure is not always instant but might take a while depending on work load etc.

**Comment by bagder** [comment]
I believe @xquery intends to update the [official curl docker image](https://hub.docker.com/r/curlimages/curl) to 7.79.1 in close association with the release as well.

**Comment by ocefpaf** [comment]
Just wanted to show some love to curl devs. Hit the issue, google, and found out that is already solved! Thanks so much!!

**Comment by theloveofcode** [comment]
It doesn't look like this fixed worked. The original example brought up by @glenndeb still throws the same error:
`curl --location --request POST 'https://id.b2b.verizonmedia.com/identity/oauth2/access_token' -v`

You can see the same thing here, where 401 is both the response code and the reason phrase.
`curl -I https://checkout-test.adyen.com/checkout/v67/paymentMethods -v`

Alpine has already updated to 7.79.1

**Comment by bagder** [comment]
@theloveofcode both those URLs work when I try them with 7.79.1 or git master

**Comment by theloveofcode** [comment]
@bagder Yes, it seems that's true. For some reason even though I'm running `apk update && apk upgrade curl` and I still see `> User-Agent: curl/7.79.1` and `* Unsupported response code in HTTP response`, newer deployments seem to work as expected.

**Comment by glenndeb** [comment]
> Just wanted to show some love to curl devs. Hit the issue, google, and found out that is already solved! Thanks so much!!

I agree, thanks for all the work and quick response!
